### PR TITLE
Add commads 'FindSuperClasses' and 'FindSubClasses'

### PR DESCRIPTION
**Pull request by dan-t**

### CODE REVIEW

**Comment by lyuts** [comment]
Thank you for this change. If you don't mind, could you add tests for FindSubClasses and FindSuperClasses functions?
Those would be helpful if the output format from ```rc``` changes.

**Comment by dan-t** [comment]
On Sun, Jun 26, 2016 at 05:12:16PM -0700, lyuts wrote:
> Thank you for this change. If you don't mind, could you add tests for
> FindSubClasses and FindSuperClasses functions?

Ok, I will take a look.

**Comment by dan-t** [comment]
On Sun, Jun 26, 2016 at 05:12:16PM -0700, lyuts wrote:
> Thank you for this change. If you don't mind, could you add tests for
> FindSubClasses and FindSuperClasses functions?
> Those would be helpful if the output format from rc changes.

Looking at the current tests, none of it uses 'rc', but just creates
artificial output of 'rc' and checks if the plugin code handles it correctly.

To really test if the 'rc' output changes, there has to be c++ test project,
which gets indexed by 'rc' and then check the output of 'rc' for this project.

I've now just added unittests with artificial data.

**Comment by lyuts** [comment]
Yes, that's correct. There is no real invocation of rc in tests, but that's the best we have at this point. Thank you for adding tests.

**Pull request merged**
