### PR TITLE
[RFC] Implement rtags#Diagnostics - display warnings and errors

### PR DESCRIPTION
**Pull request by marxin**
Hello.

I would like to help you with the project and rtags can display errors/warnings for a current file.
I prepared a patch which is a just a draft. I would like to ask whether using python3 is possible? This is my first VIM plug-in and so that I decided to parse the XML result in python.

### CODE REVIEW

**Comment by marxin** [comment]
screenshot from 2016-11-14 11-32-14

**Comment by marxin** [comment]
It's attempt to address #44

**Comment by lyuts** [comment]
Thanks a lot for helping with this. Looks good. How hard is it to make this change work with both python 2 and python3? Ideally I'd like all types of environments to be able to use this plugin. I think most of personal setups should be fine with python 3, but I came across some environments (like at work, where people have to use company provided distros) which are slightly outdated and which don't have python 3 installed at all. I'd say this is not blocking this change for now, just wish we have this case covered.

**Comment by marxin** [comment]
Hi! I'm happy that you welcome the changes, I have another items on my TODO list which can be done related to rtags#Diagnostics:
1) python2 - as you mentioned
2) it does not properly work with an unsaved content
3) as YCM does, we may want to periodically trigger the rebuild; hope an option would be feasible for that
4) define symbols for error, warning, fixit

I'm planning to return to this during Christmas time.

**Comment by lyuts** [comment]
Sounds good. Thanks again for the contribution.

**Pull request merged**
